# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 03:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashformapp.Collections')),
            ],
        ),
        migrations.CreateModel(
            name='DataViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashformapp.Collections')),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('datatype', models.CharField(choices=[(b'BOOL', b'Boolean'), (b'NUM', b'Number'), (b'TXT', b'Text')], max_length=10)),
                ('hidden', models.BooleanField(default=False)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashformapp.DataViews')),
            ],
        ),
    ]
